project:
  type: website

website:
  title: "Lodewijn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: koenpiet.qmd
        text: Ko en Piet

format:
  html:
    theme: cosmo